### ISSUE TITLE
Update data without updating company_name

### ISSUE THREAD

**Issue by jodelajo** [abczzz13/fndr_backend#18]
Hi Thomas, 
When I use patch request to update the company data, I get an error when I don't change de company_name but do change change the other values. Can you make an exception for PATCH, that it's NOT required to change the company_name when updating the other values?

See error in screenshot:
<img width="1395" alt="Schermafbeelding 2022-03-20 om 17 24 31" src="https://user-images.githubusercontent.com/74967270/159270657-16389a32-08af-4c43-aedb-2f12cee2b3dc.png">

**Comment by abczzz13** [comment]
Thank you for notifying my on this issue!

This error arises due to trying to change the company_name, which you actually don't want to change. A temporary solution for this would be to not include any fields you don't want to change in the PATCH request.

However, as the company_name is in use by the company_id you are trying to change, this validation check is unnecessary for this situation. I will look into updating this ASAP.
